List navigationData = [
  { 'icon' : 'user.png', 'title': 'User'},
  { 'icon' : 'store.png', 'title': 'Store'},
  { 'icon' : 'vip.png', 'title': 'Vip'},
  { 'icon' : 'gift.png', 'title': 'Gift'},
  { 'icon' : 'reward.png', 'title': 'Reward'},
  { 'icon' : 'guardian.png', 'title': 'Guardian'},
  { 'icon' : 'ban.png', 'title': 'Ban'},
  { 'icon' : 'level.png', 'title': 'Level'},
  { 'icon' : 'media.png', 'title': 'Media'},
  { 'icon' : 'report.png', 'title': 'Report'},
  { 'icon' : 'agency.png', 'title': 'Agency'},
  { 'icon' : 'admin.png', 'title': 'Admin'},
  { 'icon' : 'sub_admin.png', 'title': 'Sub Admin'},
  { 'icon' : 'recharge.png', 'title': 'Recharge'},
  { 'icon' : 'pk.png', 'title': 'Pk'},
  { 'icon' : 'banner.png', 'title': 'Banner'},
  { 'icon' : 'verification.png', 'title': 'Verification'},
  { 'icon' : 'salary.png', 'title': 'Salary'},
  { 'icon' : 'sticker.png', 'title': 'Sticker'},
  { 'icon' : 'setting.png', 'title': 'Settings'},
  { 'icon' : 'payment.png', 'title': 'Payment'},
  { 'icon' : 'signout.png', 'title': 'Sign Out'},
  { 'icon' : 'ads.png', 'title': 'Ads'},
];
