List navigationData = [
  {'icon': 'analyse.svg', 'title': 'Analyse', 'count': '458862'},
  {'icon': 'user.svg', 'title': 'User', 'count': '458862'},
  {'icon': 'store.svg', 'title': 'Store', 'count': '458862'},
  {'icon': 'vip.svg', 'title': 'Vip', 'count': '458862'},
  {'icon': 'gift.svg', 'title': 'Gift', 'count': '458862'},
  {'icon': 'reward.svg', 'title': 'Reward', 'count': '458862'},
  {'icon': 'guardian.svg', 'title': 'Guardian', 'count': '458862'},
  {'icon': 'ban.svg', 'title': 'Ban', 'count': '458862'},
  {'icon': 'level.svg', 'title': 'Level', 'count': '458862'},
  {'icon': 'media.svg', 'title': 'Media', 'count': '458862'},
  {'icon': 'report.svg', 'title': 'Report', 'count': '458862'},
  {'icon': 'agency.svg', 'title': 'Agency', 'count': '458862'},
  {'icon': 'admin.svg', 'title': 'Admin', 'count': '458862'},
  {'icon': 'sub_admin.svg', 'title': 'Sub Admin', 'count': '458862'},
  {'icon': 'recharge.svg', 'title': 'Recharge', 'count': '458862'},
  {'icon': 'pk.svg', 'title': 'Pk', 'count': '458862'},
  {'icon': 'banner.svg', 'title': 'Banner', 'count': '458862'},
  {'icon': 'verification.svg', 'title': 'Verification', 'count': '458862'},
  {'icon': 'salary.svg', 'title': 'Salary', 'count': '458862'},
  {'icon': 'sticker.svg', 'title': 'Sticker', 'count': '458862'},
  {'icon': 'setting.svg', 'title': 'Settings', 'count': '458862'},
  {'icon': 'payment.svg', 'title': 'Payment', 'count': '458862'},
  {'icon': 'signout.svg', 'title': 'Sign Out', 'count': '458862'},
  {'icon': 'ads.svg', 'title': 'Ads', 'count': '458862'},
];
